title: "Goalie Vault"
description: "A floorball goalie resource hub."
baseurl: "/goalie-vault" # Important if hosted in a subfolder
url: "https://brndkfr.github.io"

# Collections tell Jekyll to look into your custom folders
collections:
  articles:
    output: true
  quizzes:
    output: true

# Build settings
markdown: kramdown
theme: minima # You can change this to a cooler theme later